#!/bin/bash
#
# The program list out all files of a specified package or
# list out all packages currently installed on this host
# The program do also list all files in a package installed
#
# Status: More to come on this script....
# 
# Author: Steinar/LA7XQ
#         hack script skrevet av Steinar i full fart
#
exit_help() {
   echo  "The list package <-----vs.-----> files utility"
   echo  "Usage: $(basename $0) [-y] binary # check a binary is installed. If not, list possible package(s) to install"
   echo  "Usage: $(basename $0) -p|--pack <packet name> # check if the <package> is installed and if installed, list its files"
   echo
   echo  "ex1:   $(basename $0) tcpdump     # check if the binary  'tcpdump'  is installed and if not, list possible package(s) to install"
   echo  "ex2:   $(basename $0) -p          # list out all packages already installed on this host"
   echo  "ex3:   $(basename $0) -p dnsutils # check if the package 'dnsutils' is installed and if installed, list its files"
   exit 1
}

QUIET=1
if [ $# -ne 0 ];then
   case "$1" in
      -y) QUIET=0;shift;;
      # -p|--pack ) dpkg -L "$2"; exit 0;; # list files in an already installed package $2
      -p|--pack ) if [ -z "$2" ];then
                     echo "List of all packages already installed on $(hostname):"
                     dpkg --get-selections
                  else
                     # echo "These releated packages are already installed on $(hostname):"
                     dpkg -L "$2"; exit 0 # list all files in the already installed package $2
                  fi
                  exit 0;; 
      -h|--help ) exit_help;;
      *)  ;;
   esac
fi

if [ $# -eq 0 ];then
   echo "ERROR: Wrong usage"
   echo
   exit_help
fi

eccho() {
   echo "$(basename $0): $1"
}

which "$1"
RET=$?
echo
if [ $RET -ne 0 ];then
   echo "The binary '$1' seems NOT installed on your host $(hostname)"
   echo;echo -ne "Type ENTER if named packages for $1 is wanted searched for: ";
   [ $QUIET -ne 0 ] && read
   echo "'$1' search and found these packages:"
   # apt-cache --full search "$1"  # full meta inspection
   apt-cache search "$1"  # do not need an Inet connection
   echo;eccho "(Notice: Above package list rely on your last"
   eccho "'sudo apt-get update' done)"
   eccho "or better:"
   eccho "'sudo apt-get --fix-missing update' done)"
   echo
   eccho "Nothing is yet installed."
   eccho "Try to perform 'sudo apt-get install package' on one of the packages found abovei to install"
else
   eccho "'$1' seems installed on your host $(hostname)"
   echo 
   echo -ne "$(basename $0): File here:    $(whereis $1)";echo
   # dpkg --get-selections | grep "$1"
   echo -ne "$(basename $0): Package here: $(dpkg -S $(which "$1") | awk -F ':' '{print $1}')";echo # search inside machine to see if prog $1 is currently installed
   echo
fi


