#!/bin/bash
#
# The program tries to find out whether a program is installed or not
# and when not installed tries to find an approriate package
#
# Status: More to come on this script....
# 
# Author: Steinar/LA7XQ
#         hack script skrevet av Steinar i full fart
#
QUIET=1
if [ ! $# -eq 0 -a "$1" = "-y" ];then
   echo YES
   QUIET=0
   shift
fi

if [ $# -eq 0 ];then
   echo "ERROR: Wrong usage"
   echo "Usage: $(basename $0) [-y] <program name for checking whether installed or not>"
   echo "Ex1: $(basename $0) nslookup  # you ask whether 'nslookup' is installed or not"
   echo "Ex2: $(basename $0) -y vlc    # just run to check 'vlc' is installed or not (no question)"
   exit 1
fi

eccho() {
   echo "$(basename $0): $1"
}

which "$1"
RET=$?
echo
if [ $RET -ne 0 ];then
   eccho "'$1' seems NOT installed on your host $(hostname)"
   eccho "Type ENTER if named packages for $1 is wanted searched for: ";
   [ $QUIET -ne 0 ] && read
   echo "'$1' search and found these packages:"
   # apt-cache --full search "$1"  # full meta inspection
   apt-cache search "$1"  # do not need an Inet connection
   echo;eccho "(Notice: Above package list rely on your last"
   eccho "'sudo apt-get update' done)"
   eccho "or better:"
   eccho "'sudo apt-get --fix-missing update' done)"
   echo
   eccho "Try to perform 'sudo apt-get install package' on one of the packages found above"
else
   eccho "'$1' seems installed on your host $(hostname)"
   echo 
   echo -ne "$(basename $0): File here:    $(whereis $1)";echo
   # dpkg --get-selections | grep "$1"
   echo -ne "$(basename $0): Package here: $(dpkg -S $(which "$1"))";echo # search inside machine to see if prog $1 is currently installed
   echo
fi

