#!/bin/bash
#
# Author: Steinar/LA7XQ
#
echo "============== HW ============:"
cat /proc/cpuinfo | grep -E "(Serial|Revision)"
cat << EOF > /tmp/rpi_models
0002	Q1 2012	B	1.0	256 MB	
0003	Q3 2012	B (ECN0001)	1.0	256 MB	Fuses mod and D14 removed
0004	Q3 2012	B	2.0	256 MB	(Mfg by Sony)
0005	Q4 2012	B	2.0	256 MB	(Mfg by Qisda)
0006	Q4 2012	B	2.0	256 MB	(Mfg by Egoman)
0007	Q1 2013	A	2.0	256 MB	(Mfg by Egoman)
0008	Q1 2013	A	2.0	256 MB	(Mfg by Sony)
0009	Q1 2013	A	2.0	256 MB	(Mfg by Qisda)
000d	Q4 2012	B	2.0	512 MB	(Mfg by Egoman)
000e	Q4 2012	B	2.0	512 MB	(Mfg by Sony)
000f	Q4 2012	B	2.0	512 MB	(Mfg by Qisda)
0010	Q3 2014	B+	1.0	512 MB	(Mfg by Sony)
0011	Q2 2014	Compute Module	1.0	512 MB	(Mfg by Sony)
0012	Q4 2014	A+	1.1	256 MB	(Mfg by Sony)
0013	Q1 2015	B+	1.2	512 MB	 ?
0014	Q2 2014	Compute Module	1.0	512 MB	(Mfg by Embest)
0015	 ?	A+	1.1	256 MB / 512 MB	(Mfg by Embest)
a01040	Unknown	2 Model B	1.0	1 GB	Unknown
a01041	Q1 2015	2 Model B	1.1	1 GB	(Mfg by Sony)
a21041	Q1 2015	2 Model B	1.1	1 GB	(Mfg by Embest)
a22042	Q3 2016	2 Model B (with BCM2837)	1.2	1 GB	(Mfg by Embest)
900021	 ?	A+	1.1	512 MB	 ?
900092	Q4 2015	Zero	1.2	512 MB	(Mfg by Sony)
900093	Q2 2016	Zero	1.3	512 MB	(Mfg by Sony)
920093	Q4 2016?	Zero	1.3	512 MB	(Mfg by Embest)
a02082	Q1 2016	3 Model B	1.2	1 GB	(Mfg by Sony)
a22082	Q1 2016	3 Model B	1.2	1 GB	(Mfg by Embest)
EOF
rev=$(sudo cat /proc/cpuinfo | grep -i "^revision" | awk '{print $NF}')
[ -z "$rev" ] && { echo "This PC is likely not an RPI PC"; exit 1; }
line=$(grep $rev /tmp/rpi_models)
echo "line=$line"
model=$(echo $line | awk '{ print $4,$5,$6}')
echo "$line ==> RPI $model"
echo;echo "============== OS/DISTRO ============:"
cat /etc/*rel*
echo;echo "============== KERNEL INFO: =========:"
uname -a
rm -f /tmp/rpi_models
exit 0
