#!/bin/bash
#
# Author: Steinar/LA7XQ
#
if [ $# -ne 0 ];then
   echo $1 | grep -q -oE "\-h"
   if [ $? -eq 0 ];then
      echo "Usage: $(basename $0) [-q ]"
      echo "ex1:   $(basename $0) -q # quiet mode, no questions asked"
      echo "ex2:   $(basename $0)    # prints RPI model and ask you for more"
      exit 1
   fi
fi
QUIETMODE=0
[ $# -ne 0 ] && QUIETMODE=1
echo "============== HW ============:"
cat /proc/cpuinfo | grep -E "(Serial|Revision)"
cat << EOF > /tmp/rpi_models
0002	Q1 2012	B	1.0	256 MB  (Mfg by Egoman)	
0003	Q3 2012	B (ECN0001)	256 MB	(Mfg by Egoman) Fuses mod and D14 removed
0004	Q3 2012	B	2.0	256 MB	(Mfg by Sony)
0005	Q4 2012	B	2.0	256 MB	(Mfg by Qisda)
0006	Q4 2012	B	2.0	256 MB	(Mfg by Egoman)
0007	Q1 2013	A	2.0	256 MB	(Mfg by Egoman)
0008	Q1 2013	A	2.0	256 MB	(Mfg by Sony UK)
0009	Q1 2013	A	2.0	256 MB	(Mfg by Qisda)
000d	Q4 2012	B	2.0	512 MB	(Mfg by Egoman)
000e	Q4 2012	B	2.0	512 MB	(Mfg by Son UK)
000f	Q4 2012	B	2.0	512 MB	(Mfg by Qisda)
0010	Q3 2014	B+	1.0	512 MB	(Mfg by Sony UK)
0011	Q2 2014	CM1	1.0	512 MB	(Mfg by Sony)
0012	Q4 2014	A+	1.1	256 MB	(Mfg by Sony UK)
0013	Q1 2015	B+	1.2	512 MB	 ?
0014	Q2 2014	CM1	1.0	512 MB	(Mfg by Embest)
0015	?	A+	1.1	256 MB/512 MB	(Mfg by Embest)
a01040	Unknown	2 Model B	1.0	1 GB	(Mfg by Sony UK)
a01041	Q1 2015	2 Model B	1.1	1 GB	(Mfg by Sony UK)
a21041	Q1 2015	2 Model B	1.1	1 GB	(Mfg by Embest)
a22042	Q3 2016	2 Model B (with BCM2837)	1.2	1 GB	(Mfg by Embest)
900021	 ?	A+	1.1	512 MB	(Mfg by Sony UK)
900032	 ?	B+	1.2	512 MB	(Mfg by Sony UK)
900092	Q4 2015	Zero	1.2	512 MB	(Mfg by Sony UK)
900093	Q2 2016	Zero	1.3	512 MB	(Mfg by Sony UK)
9000c1	Q2 2016	Zero W	1.1	512 MB	(Mfg by Sony UK)
920093	Q4 2016?	Zero	1.3	512 MB	(Mfg by Embest)
a02082	Q1 2016	3 Model B	1.2	1 GB	(Mfg by Sony UK)
a22082	Q1 2016	3 Model B	1.2	1 GB	(Mfg by Embest)
a020a0 	Q1 2016	CM3	 	1.0	1 GB	(Mfg by Sony UK)
a32082 	-  -    3 Model B       1.2     1 GB   (Mfg by Sony Japan)
3a01041 -  -    2 Model B       -       1 GB    - 
a020d3  - 2018  3 Model B+              1 GB    -
9020e0	Q4 2018	3 Model A+	1.0	512 MB	(Mfg by Sony)
EOF
rev=$(sudo cat /proc/cpuinfo | grep -i "^revision" | awk '{print $NF}')
[ -z "$rev" ] && { echo "This PC is likely not an RPI PC"; exit 1; }
line=$(grep $rev /tmp/rpi_models)
model=$(echo $line | awk '{ print $4,$5,$6}')
echo "$line ==> RPI $model"
if [ $QUIETMODE -eq 0 ];then
   echo;echo "Type ENTER to continue with OS, KERNEL and CPU info"
   read
fi

echo;echo "============== OS/DISTRO ============:"
cat /etc/*rel*
echo;echo "============== KERNEL INFO: =========:"
uname -a
rm -f /tmp/rpi_models
if [ -f $(which lscpu) ];then
   echo;echo "============== CPU INFO: ============:"
   $(which lscpu)
fi
exit 0
