#!/bin/bash
#
# The program gives vendor overview on the local (private LAN network)
# The program also perform arp scan.....
#
# Author: Steinar/LA7XQ
#

TMP1="./arp.tmp1"
OUIFILE="$HOME/oui.txt"
NOOFSCANS=100

exit_help() {
   echo;echo "Usage: $(basename $0) [<OPTIONS>]"
   echo "OPTIONS ARE:"
   echo "$(basename $0) -h|--help # print help"
   echo "$(basename $0) -k|--keep # keep on scanning $NOOFSCANS scans"
   [ -f $TMP1 ] && rm -f $TMP1  # cleanup if ever used
   exit 1
}
echo;echo " ---- Vendor information ----"
if [ $# -ne 0 ];then
   case "$1" in
      -k|--keep) ;;
      *)         exit_help;;  # includes -h|--h
   esac
   echo "will now perform scan $NOOFSCANS times..."
   echo "Stop by typing Ctrl C"
else
   # default is just running 2 scans
   NOOFSCANS=2
fi

if [ ! -f $OUIFILE ];then
   echo "$(basename $0):ERROR: File $OUIFILE not found"
   echo "Perform first an 'cd $HOME;rm -f oui.txt*;wget http://standards.ieee.org/develop/regauth/oui/oui.txt;bash rpi/getvendor;cd $HOME/rpi' on your RPI"
   echo "Now exit"
   exit 1
fi
if [ ! -f /usr/bin/arp-scan ];then
   echo "$(basename $0):ERROR: /usr/bin/arp-scan not found"
   echo "Install by 'sudo apt-get install arp-scan' first. Now exit"
   exit 1
fi   

MAC=$(ip addr  | grep -E ".*ether.*\b([0-9a-fA-F]{1,2}\:){5}([0-9a-fA-F]{1,2})\b" | \
awk -F "ether" '{print $2}' | awk '{print $1}');
OWNMAC=$(echo "$MAC" | head -n 1 | awk -F ":" '{print $1,$2,$3}' | tr -d " ")
THREEUPPER=$(echo "$OWNMAC" | tr "[a-f]" "[A-F]")
#echo "THREEUPPER=$THREEUPPER"
echo
FIRSTL=$(ip addr | egrep -e "inet.*global" | grep -E "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" | awk '{print "Your IP LAN addr:  ", $2,$NF,"  "}')
echo -ne "$FIRSTL"
grep "$THREEUPPER" $OUIFILE | tr "[  \t]" " "

#ip addr | egrep -e "inet.*global" | grep -E "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" | awk '{print "    ", $2,$NF}'
for num in $(seq 1 $NOOFSCANS);do
   echo;echo -n " ---- SCAN $num for others on the LAN network ------:";echo
 
   sudo arp-scan --retry=6 --ignoredups --localnet > $TMP1

   RET=$?
   [ $RET -ne 0 ] && { echo "$(basename $0): ERROR: Can't arp scan. Can't connect to network"; exit 1; }
   while IFS='' read -r line || [[ -n "$line" ]]; do
      if echo $line | grep -q -E ":.*:.*:.*:";then
          printf $(echo "$line" | awk '{print $1}')
          printf "   "
          # printf $(echo "$line" | awk '{print $2}')
          # printf "   "
          MAC=$(echo "$line" | awk '{print $2}')
          OUI=$(echo ${MAC//[:.- ]/} | tr "[a-f]" "[A-F]" | egrep -o "^[0-9A-F]{6}")
          OUUT=$(grep "$OUI" $OUIFILE) # wget http://standards.ieee.org/develop/regauth/oui/oui.txt

          printf " "
          grep "$OUUT" $OUIFILE # wget http://standards.ieee.org/develop/regauth/oui/oui.txt
      fi
   done < "$TMP1"
done
[ -f $TMP1 ] && rm -f $TMP1  # cleanup
echo;echo "(You may also try 'bash $(basename $0) --help'    to have more options)"
